<a href="https://colab.research.google.com/github/VinoJose/Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


###Creating tensors

In [3]:
#create scalar with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [5]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#check the dimentions of out vector
vector.ndim

1

In [7]:
#create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [11]:
#create another matrix
another_matrix = tf.constant([[10.,9.],
                              [9.,10.],
                              [3.,2.]],dtype=tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  9.],
       [ 9., 10.],
       [ 3.,  2.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [14]:
#create a tensor
tensor = tf.constant([[[1,2,4],
                       [2,3,4]],
                      [[3,4,5],
                       [4,5,6]],
                      [[5,6,7],
                       [6,7,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]],

       [[5, 6, 7],
        [6, 7, 8]]], dtype=int32)>

In [15]:
tensor.ndim

3

###Create tensor using `tf.Variable`

In [17]:
#create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# try changing elements in these tensors
changeable_tensor[0] =7

In [19]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0] = 7

We can only change the values of tensors which are created using `tf.Variable()`. 

###Creating random tensors

In [25]:
#create 2 random (but same) tensors
random1 = tf.random.Generator.from_seed(7)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(7)
random2 = random2.normal(shape=(3,2))

#Are they equal?
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor

In [26]:
#Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [2,4],
                            [5,7]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 5,  7],
       [10,  7]], dtype=int32)>

In [40]:
#Shuffle with a seed

tf.random.set_seed(53) # global level random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  7],
       [ 2,  4]], dtype=int32)>

While using a set_seed, shuffled order is reproducable.



In [47]:
tf.random.shuffle(not_shuffled, seed = 53) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  7],
       [ 2,  4],
       [10,  7]], dtype=int32)>