<a href="https://colab.research.google.com/github/VinoJose/Tensorflow/blob/main/08_introduction_to_nlp_in_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NLP fundamentals in TensorFlow

## Check the GPU instance

In [1]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-066ec240-8216-33a3-0943-e962396c0476)


## Get helper functions

In [2]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

# Import series of helper functions for the notebook
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

--2022-06-21 11:37:10--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2022-06-21 11:37:10 (80.7 MB/s) - ‘helper_functions.py’ saved [10246/10246]



## Get a text dataset

The dataset we are going to be using is Kaggle's introduction to NLP dataset (text samples of Tweets labelled as disaster or not disaster)

In [3]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

# Unzip data
unzip_data("nlp_getting_started.zip")

--2022-06-21 11:37:13--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.1.128, 108.177.121.128, 142.250.103.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.1.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.005s  

2022-06-21 11:37:13 (116 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



## Visualizing a text dataset

In [4]:
import pandas as pd
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [5]:
# Shuffle the training dataset
train_df_shuffled = train_df.sample(frac=1, random_state=42)
train_df_shuffled.head()


id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [6]:
 # What does the test dataset look like?
 test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [7]:
# How many examples of each class?
train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [8]:
# How many total samples?
len(train_df), len(test_df)

(7613, 3263)

In [9]:
# Let's visualize some random examples
import random
random_index = random.randint(0, len(train_df)-5)
for row in train_df_shuffled[["text", "target"]][random_index:random_index+5].itertuples():
  #print(row)
  _, text, target = row
  print(f"Target:{target}", "(real disaster)" if target > 0 else "(not real disaster)")
  print(f"Text:\n{text}\n")
  print("----\n")

Target:0 (not real disaster)
Text:
@sethalphaeus my personal favorites include paramore muse green day royal blood and 5sos

----

Target:1 (real disaster)
Text:
@FlyOpineMonkey You mean Olympic ;-) 
Also its follow-up for Honshu Operation Coronet. 
In all: 1m Allied casualties 30m Japanese dead.

----

Target:0 (not real disaster)
Text:
Fairfax investigating firefighter over Facebook post saying police should be put in ‰Û÷body bags‰Ûª - The Washington Post http://t.co/jAxHzjCCd4

----

Target:0 (not real disaster)
Text:
RT @RTRRTcoach: #Love #TrueLove #romance lith  #Voodoo #seduction #Astrology #RTRRT #LOTZ 9-11 #apocalypse #Armageddon #1008planet‰Û_

----

Target:1 (real disaster)
Text:
BLOG: Rain much needed as drought conditions worsen: Right now Charlotte and much of the surrounding area have‰Û_ http://t.co/OLzaVTJFKH

----



### Split data into training and validation sets

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
# Use train_test_split to split training data into training and validation sets
train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                            train_df_shuffled["target"].to_numpy(),
                                                                            test_size=0.1,
                                                                            random_state=42)


In [12]:
# Check the lengths
len(train_sentences), len(val_sentences), len(train_labels), len(val_labels)

(6851, 762, 6851, 762)

In [13]:
# Check the first 10 samples
train_sentences[:10], train_labels[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object), array([0, 

### Converting text to numbers

### Text vectorization (Tokenization)

In [14]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

# Use default text vertorization parameters
text_vectorizer = TextVectorization(max_tokens=None,
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None,
                                    output_mode="int",
                                    output_sequence_length=None,
                                    pad_to_max_tokens=False)

In [15]:
# Find the average number of words in the training tweets
round(sum(len(i.split()) for i in train_sentences)/len(train_sentences))

15

In [16]:
# Setup the text vectorization variables
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 15 # max number of words in our sequence

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [17]:
# Fit the vectorizer to the training data
text_vectorizer.adapt(train_sentences)

In [18]:
# Create a sample sentence and tokenize it
sample_sentence = "There's a flood in my street!"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[264,   3, 232,   4,  13, 698,   0,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [19]:
# Choose a random sentence from the training set and tokenize it
random_sentence = random.choice(train_sentences)
print(f"Original sentence:{random_sentence} \n Vectorized sentence:")
text_vectorizer([random_sentence])

Original sentence:How to restore vinyl siding and make it look new again http://t.co/MHL7Pfr7kb http://t.co/lou8lbLA1f 
 Vectorized sentence:


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[  62,    5, 2313, 1926, 4625,    7,  144,   15,  173,   50,  282,
           1,    1,    0,    0]])>

In [20]:
# Get the unique words in the vocabulary
words_in_vocab = text_vectorizer.get_vocabulary()
top_5_words = words_in_vocab[:5]
bottom_5_words = words_in_vocab[-5:]

In [21]:
print(f"The number of words in the vocab: {len(words_in_vocab)}")
print(f"The top 5 common words in the vocab: {top_5_words}")
print(f"The bottom 5 common words in the vocab: {bottom_5_words}")

The number of words in the vocab: 10000
The top 5 common words in the vocab: ['', '[UNK]', 'the', 'a', 'in']
The bottom 5 common words in the vocab: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']


### Creating an Embedding using Embedding layer

In [22]:
 from tensorflow.keras import layers

 embedding = layers.Embedding(input_dim=max_vocab_length,
                              output_dim=128,
                              input_length=max_length)
 embedding

In [23]:
# Get a random sentence from the training set
random_sentence = random.choice(train_sentences)

print(f"Original sentence: \n{random_sentence} \n\nEmbedded version:")

# Embed the random sentence (turn it into dence vectors of fixed size)
sample_embed = embedding(text_vectorizer(random_sentence))
sample_embed

Original sentence: 
'Fatal crash reported on Johns Island' http://t.co/d2i9bL89Zo 

Embedded version:


<tf.Tensor: shape=(15, 128), dtype=float32, numpy=
array([[-0.03111959, -0.0314314 ,  0.03131087, ..., -0.041471  ,
         0.02142639,  0.01348777],
       [ 0.0034949 ,  0.0164918 ,  0.0041088 , ..., -0.01388934,
         0.03192725,  0.03819035],
       [ 0.01067331,  0.0346468 , -0.04362048, ...,  0.02012409,
        -0.00962675,  0.01232011],
       ...,
       [-0.01915581,  0.00142182, -0.00069607, ...,  0.02489195,
        -0.04235333,  0.03146524],
       [-0.01915581,  0.00142182, -0.00069607, ...,  0.02489195,
        -0.04235333,  0.03146524],
       [-0.01915581,  0.00142182, -0.00069607, ...,  0.02489195,
        -0.04235333,  0.03146524]], dtype=float32)>

## Modeling a text dataset (running a series of experiments)

Now we know how to turn text data to series of numbers. We can now start a series of model building experiments.

We'll start with a baseline and move on from there.

### Model 0: Getting a baseline

As with all machine learning experiments, let's create a baseline model. We can create baseline model with SKlearn's Naive Bayes using TF-IDF


In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create tokenization and modelling pipeline
model_0 = Pipeline([
                    ("tfidf", TfidfVectorizer()),
                    ("clf", MultinomialNB())  
])

# Fit the pipeline to the training data
model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [25]:
# Evaluate our baseline model
baseline_score = model_0.score(val_sentences, val_labels)
print(f"Out baseline model achieves an accuracy of: {baseline_score*100:.2f}%")

Out baseline model achieves an accuracy of: 79.27%


In [26]:
# Make predictions
baseline_preds = model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

### Creating an evaluation function for our model experiments

In [27]:
# Function to evaluate: accuracy, precision, recall, f1-score
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):
  """
  Calculates the model accuracy, precision, recall and f1 score for a binary classifier
  """
  model_accuracy = accuracy_score(y_true, y_pred)

  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average= 'weighted')
  model_results = {'accuracy' : model_accuracy,
                   'precision' : model_precision,
                   'recall' : model_recall,
                   'f1' : model_f1}
  return model_results


In [28]:
# Get baseline results
baseline_results = calculate_results(y_true=val_labels,
                                     y_pred=baseline_preds)
baseline_results

{'accuracy': 0.7926509186351706,
 'f1': 0.7862189758049549,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706}

 ### Model 1: A simple dense model

In [29]:
 # Create a tensorboard callback 
 from helper_functions import create_tensorboard_callback

 # Create a directory to save tensorboard logs
 SAVE_DIR = "model_logs "

In [37]:
# Build model with functional API
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.GlobalAveragePooling1D()(x) # condense the feature vector for each token to one vector 
outputs = layers.Dense(1,activation="sigmoid")(x)
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense")

In [38]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d (G  (None, 128)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense_2 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
N

In [39]:
# Compile the model
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [40]:
# Fit the model
model_1.fit(x=train_sentences,
            y=train_labels,
            epochs=5,
            validation_data=[val_sentences, val_labels],
            callbacks=[create_tensorboard_callback(dir_name= SAVE_DIR,
                                                  experiment_name="model_1_dense")])

Saving TensorBoard log files to: model_logs /model_1_dense/20220621-121403
Epoch 1/5
215/215 [==============================] - 5s 5ms/step - loss: 0.6113 - accuracy: 0.6941 - val_loss: 0.5361 - val_accuracy: 0.7612
Epoch 2/5
215/215 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.8181 - val_loss: 0.4728 - val_accuracy: 0.7808
Epoch 3/5
215/215 [==============================] - 1s 4ms/step - loss: 0.3465 - accuracy: 0.8609 - val_loss: 0.4567 - val_accuracy: 0.7927
Epoch 4/5
215/215 [==============================] - 1s 5ms/step - loss: 0.2845 - accuracy: 0.8902 - val_loss: 0.4616 - val_accuracy: 0.7822
Epoch 5/5
215/215 [==============================] - 1s 4ms/step - loss: 0.2377 - accuracy: 0.9108 - val_loss: 0.4799 - val_accuracy: 0.7874


In [41]:
# Check the results
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 5ms/step - loss: 0.4799 - accuracy: 0.7874


[0.4798620045185089, 0.787401556968689]

In [46]:
# See predictions
model_1_preds_probs= model_1.predict(val_sentences)
model_1_preds_probs[:5]

array([[0.3680693 ],
       [0.7924704 ],
       [0.99723345],
       [0.1107293 ],
       [0.10218651]], dtype=float32)

In [49]:
# Convert model prediction probabilities to label format
model_1_preds = tf.squeeze(tf.round(model_1_preds_probs))
model_1_preds[:5]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 1., 0., 0.], dtype=float32)>

In [50]:
# Calculate model 1 results
model_1_results = calculate_results(y_true=val_labels,
                                    y_pred=model_1_preds)
model_1_results

{'accuracy': 0.7874015748031497,
 'f1': 0.7842639469124086,
 'precision': 0.7927656871284042,
 'recall': 0.7874015748031497}